submodule network {
    belongs-to v1 {
        prefix "v1";
    }

    import ietf-inet-types {
        prefix "inet";
    }

    container ipv4 {
        list entrys {
            key "name ip";
            leaf name {
                type string {
                    pattern '[-0-9a-zA-Z.]{3,63}';
                }
            }
            leaf ip {
                mandatory true;
                type inet:ipv4-address;
            }
            leaf mask {
                mandatory true;
                type uint8 {
                    range "0 .. 32";
                }
                description "A mask value from 0 to 32 inclusive.";
            }
            leaf type {
                mandatory true;
                type enumeration {
                    enum IP_MASTER {
                        value 0;
                    }
                    enum IP_SECONDARY {
                        value 1;
                    }
                }
            }
        }
    }

    container route_v4 {
        list entrys {
            key "net mask";

            leaf net {
                mandatory true;
                type inet:ipv4-address;
            }

            leaf mask {
                mandatory true;
                type uint8 {
                    range "0 .. 32";
                }
                description "A mask value from 0 to 32 inclusive.";
            }

            leaf nexthop {
                mandatory true;
                type inet:ipv4-address;
            }

            leaf interface_name {
                type string {
                    pattern '[-0-9a-zA-Z.]{3,63}';
                }
            }
        }
    }
}
